# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      
    - name: Check Go version
      run: go version

    - name: Run Server
      run: |
        go run main.go &
        sleep 5s
    
    - name: Curl
      run: | 
        curl -v localhost
        curl -X POST -d 'body content' localhost/body
        curl -X POST -F 'color=black' localhost/form
        curl -X POST -d 'color=black&shape=round' -H "Content-Type: application/x-www-form-urlencoded" localhost/formall
