# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run Server Locally

env:
  PORT: 8080

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      
    - name: Check Go version
      run: go version

    - name: Run Server
      run: |
        go run main.go $PORT
        sleep 10s
        API_URI=localhost:$PORT
        curl -v $API_URI
        
    - name: Curl
      run: | 
        API_URI=localhost:$PORT
        curl -v $API_URI
        curl -X POST -d 'body content' $API_URI/body
        curl -X POST -F 'color=black' $API_URI/form
        curl -X POST -d 'color=black&shape=round' -H "Content-Type: application/x-www-form-urlencoded" $API_URI/formall
