# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run Server Locally

env:
  PORT: 8080

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      
    - name: Check Go version
      run: go version

    - name: Run Server
      run: |
        go run main.go $PORT &
        sleep 30s
        echo "API_URI=localhost:$PORT" >> $GITHUB_ENV

    # Curl parts of API    
    - name: Curl Home
      run: curl -v ${{ env.API_URI }}
    
    - name: Curl Body
      run: curl -X POST -d 'body content' ${{ env.API_URI }}/body
    
    - name: Curl Form Value
      run: curl -X POST -F 'color=black' ${{ env.API_URI }}/form
    
    - name: Curl Parse Form
      run: |
        curl -X POST -d "color=black&shape=round" -H "Content-Type: application/x-www-form-urlencoded" ${{ env.API_URI }}/formall
